version: 0.0
os: linux
files:
- source: .
  destination: /var/www/lol
hooks:
  ApplicationStart:
#  - location: scripts/start_application.sh
  - location: start_application.sh
    timeout: 300
    runas: root
  ApplicationStop:
  - location: stop_application.sh
    timeout: 300
    runas: root