version: 0.0
os: linux
files:
- source: ./my-app-1.0-SNAPSHOT.jar
  destination: /var/www/html/result
hooks:
  ApplicationStart:
  - location: scripts/start_application.sh
    timeout: 300
    runas: root
  ApplicationStop:
  - location: scripts/stop_application.sh
    timeout: 300
    runas: root