version: 0.0
os: linux
files:
- source: .
  destination: /var/www/
hooks:
  ApplicationStart:
  - location: scripts/start_application.sh
    timeout: 300
    runas: root
  ApplicationStop:
  - location: scripts/stop_application.sh
    timeout: 300
    runas: root