version: 0.2

phases:
  build:
    commands:
    - echo Build started on `date`
    - mvn test
  post_build:
    commands:
    - echo Build completed on `date`
    - mvn package
artifacts:
  files:
  - target/demo-0.0.1-SNAPSHOT.jar
  - appspec.yml
  - scripts/start_application.sh
  - scripts/stop_application.sh
  discard-paths: yes